"""
report.py — emit a Markdown audit report from a list of findings.

The report is intentionally human-readable and copy-paste friendly; you
can paste it into a PR description, a Notion page, or attach it to an
Upwork deliverable.
"""

from __future__ import annotations

import datetime as _dt
from collections import Counter
from pathlib import Path
from typing import Iterable

from .risk_patterns import Finding


_SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2}


def _summary_table(findings: list[Finding]) -> list[str]:
    by_sev = Counter(f.severity for f in findings)
    by_cat = Counter(f.category for f in findings)
    lines = []
    lines.append("| Metric | Count |")
    lines.append("| --- | ---: |")
    lines.append(f"| **Total findings** | {len(findings)} |")
    for sev in ("high", "medium", "low"):
        lines.append(f"| {sev.title()} severity | {by_sev.get(sev, 0)} |")
    for cat in sorted(by_cat):
        lines.append(f"| Category: {cat} | {by_cat[cat]} |")
    return lines


def _by_category(findings: list[Finding]) -> Iterable[tuple[str, list[Finding]]]:
    by: dict[str, list[Finding]] = {"architecture": [], "security": [], "testing": [], "gdpr": []}
    for f in findings:
        by.setdefault(f.category, []).append(f)
    for k in sorted(by):
        yield k, sorted(by[k], key=lambda f: (_SEVERITY_ORDER.get(f.severity, 9), f.file, f.line))


def _escape_table(text: str) -> str:
    # Markdown tables can't contain newlines or pipe characters.
    text = text.replace("|", "\\|").replace("\n", " ").strip()
    if len(text) > 160:
        return text[:157] + "..."
    return text


def _table_for(category: str, items: list[Finding]) -> list[str]:
    lines: list[str] = []
    lines.append(f"### {category.title()} ({len(items)})")
    if not items:
        lines.append("")
        lines.append("_No findings in this category._")
        lines.append("")
        return lines
    lines.append("")
    lines.append("| # | Sev | Title | File | Line | Snippet |")
    lines.append("| --- | --- | --- | --- | ---: | --- |")
    for i, f in enumerate(items, 1):
        lines.append(
            f"| {i} | {f.severity} | `{f.id}` {f.title} | "
            f"`{_escape_table(f.file)}` | {f.line} | "
            f"`{_escape_table(f.snippet)}` |"
        )
    lines.append("")
    return lines


def _group_by_id(findings: list[Finding]) -> list[tuple[str, str, str]]:
    """Return human-readable rationale lines, deduplicated by (id, rationale)."""
    out: list[tuple[str, str, str]] = []
    seen: set[tuple[str, str]] = set()
    for f in findings:
        key = (f.id, f.rationale)
        if key in seen:
            continue
        seen.add(key)
        out.append((f.id, f.title, f.rationale))
    return out


def render(findings: list[Finding], repo_path: Path, *, repo_label: str | None = None) -> str:
    repo_label = repo_label or str(repo_path)
    high = [f for f in findings if f.severity == "high"]
    timestamp = _dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"

    parts: list[str] = []
    parts.append(f"# Lovable-MVP Audit — `{repo_label}`")
    parts.append("")
    parts.append(f"_Generated by `lovable-audit` v0.1.0 at {timestamp}._")
    parts.append("")
    parts.append("This is a **generic scaffold audit** for a Next.js + Supabase +")
    parts.append("Lovable-style SaaS. The findings below are rule-based and are")
    parts.append("**a starting point**, not a substitute for an experienced human")
    parts.append("review. Review the rationale, then triage against your roadmap.")
    parts.append("")
    parts.append("---")
    parts.append("")
    parts.append("## TL;DR")
    parts.append("")
    parts.extend(_summary_table(findings))
    parts.append("")
    if high:
        parts.append(f"**{len(high)} high-severity item(s)** — recommend resolving before public launch.")
        parts.append("")
    parts.append("## Top actions")
    parts.append("")
    for fid, title, rationale in _group_by_id(high)[:8]:
        parts.append(f"- **{fid} — {title}.** {rationale}")
    parts.append("")
    parts.append("---")
    parts.append("")

    for category, items in _by_category(findings):
        parts.extend(_table_for(category, items))

    parts.append("---")
    parts.append("")
    parts.append("## How to use this report")
    parts.append("")
    parts.append("1. Copy the risk register at `templates/risk_register.md` and tick items as you triage.")
    parts.append("2. Address `high` severity findings before the next public release.")
    parts.append("3. Re-run `lovable-audit <repo>` after fixes and compare diff in `report.md`.")
    parts.append("4. Use `templates/production_readiness_checklist.md` for launch readiness.")
    parts.append("")

    return "\n".join(parts)


def write_report(findings: list[Finding], repo_path: Path, out_path: Path, *, repo_label: str | None = None) -> Path:
    md = render(findings, repo_path, repo_label=repo_label)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    return out_path
